### ISSUE TITLE
Crash when saving

### ISSUE THREAD

**Issue by pianoman373** [ParkerMc/minecraft-map-gen#1]
**Got a crash when trying to render a world. Here's the log:**

2016-06-06 16:18:04 E Syntax error parsing C:/Users/Joseph/Desktop/32bit/test.cfg
2016-06-06 16:18:04 E The traceback below will tell you which line triggered the syntax error
2016-06-06 16:18:04 E Partial traceback:
Traceback (most recent call last):
File "overviewer_core\configParser.pyc", line 82, in parse
File "C:/Users/Joseph/Desktop/32bit/test.cfg", line 20
outputdir = "C:/Users/Joseph/Desktop/32bit/output""
^
SyntaxError: EOL while scanning string literal

**And here is my save cfg file:**
# Made with a generator by ParkerMc
#### Do NOT edit
# C:\Users\Joseph\Desktop\32bit\output
# E:/.minecraft/versions/1.9.4/1.9.4.jar
#1
# mumbo world, E:/.minecraft/saves/Mumbo Jumbo Redstone World/level.dat
# test, mumbo world, Overworld, Normal, Upper Left, Png, 95

worlds["world_mumbo world"] = "E:/.minecraft/saves/Mumbo Jumbo Redstone World/"
renders["test"] = {
    "world": "world_mumbo world",
    "title": "test",
    "rendermode": "normal",
    "dimension": "overworld",
    "northdirection" : "upper-left",
    "imgformat" : "png",
    "imgquality" : "95",
 } 

outputdir = "C:/Users/Joseph/Desktop/32bit/output""
texturepath = "E:/.minecraft/versions/1.9.4/1.9.4.jar"

**Comment by ParkerMc** [comment]
@pianoman373 I do not see any thing but try changing
output += 'outputdir = "'+str(self.outputt.text()).replace("\\","/")+'"'
To
output += 'outputdir = "'+str(self.outputt.text())+'"'

**Comment by ParkerMc** [comment]
Nvm you are using the exe

**Comment by ParkerMc** [comment]
Nvm I found it
