### ISSUE TITLE
Crash When Saving

### ISSUE THREAD

**Issue by Kalman98** [ParkerMc/minecraft-map-gen#3]
On Linux(Ubuntu), when I click to save and run, I get this in the log:

```
1-1-w1
1-1-w1
Traceback (most recent call last):
  File "/home/kalman98/Desktop/Minecraft Map Generator/minecraft-map-gen/Main.py", line 654, in run
    line = proc.stdout.readline()
UnboundLocalError: local variable 'proc' referenced before assignment
```

It stays frozen after that and I have close it.

**Comment by ParkerMc** [comment]
Try these
git pull
git checkout ParkerMc-patch-3
And that will load the branch with the patch

**Comment by Kalman98** [comment]
Tested the patch, upon saving and running the GUI gave me this message:

```
You need to compile the c_overviewer module to run Minecraft Overviewer.
Run `python setup.py build`, or see the README for details.
```

and the terminal gave me this:

```
You need to compile the c_overviewer module to run Minecraft Overviewer.
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
Run `python setup.py build`, or see the README for details.
```

It stayed frozen after that, like before, and never output a file(besides the config that is). I tried running the command it suggested, as well as capitalizing the 's' in setup to match the actual file name, but that did not work, and the README was not helpful either.

**Comment by ParkerMc** [comment]
Hehe sorry I made it download the wrong one.

**Comment by ParkerMc** [comment]
Ok so there is no download for Linux in general for overviwer so just download and install from here. https://overviewer.org/downloads
Then run git pull to get the changes that I made.

**Comment by ParkerMc** [comment]
Oh and run `git checkout master` I removed the patch branch

**Comment by ParkerMc** [comment]
Hello! 

Have you already  read my new article about the elections? You've got  to take  a look, here is the link <http://velteslefra.computershopmd.com/e3suug>


nick

**Comment by PieCoder314** [comment]
I thought we already had this cleared up. What happened Nick?
